# Static ticker → company name lookup. Covers the full UNIVERSE in settings.py.
# Update when tickers are added/renamed.
COMPANY_NAMES = {
    # Mega-cap tech
    "AAPL": "Apple", "MSFT": "Microsoft", "NVDA": "NVIDIA", "GOOGL": "Alphabet",
    "GOOG": "Alphabet (C)", "AMZN": "Amazon", "TSLA": "Tesla",
    "AVGO": "Broadcom", "ORCL": "Oracle", "CRM": "Salesforce", "AMD": "AMD",
    "INTC": "Intel", "CSCO": "Cisco", "ADBE": "Adobe",
    "NOW": "ServiceNow", "TXN": "Texas Instruments", "HPQ": "HP Inc.",
    "DELL": "Dell", "ARM": "Arm Holdings",
    # Semiconductors
    "MU": "Micron", "AMAT": "Applied Materials", "KLAC": "KLA Corp",
    "MCHP": "Microchip Tech", "MPWR": "Monolithic Power", "ON": "ON Semi",
    "STX": "Seagate", "WDC": "Western Digital", "MRVL": "Marvell Tech",
    "ADI": "Analog Devices", "SWKS": "Skyworks", "QRVO": "Qorvo", "WOLF": "Wolfspeed",
    "SMCI": "Super Micro", "ACLS": "Axcelis Tech", "COHU": "Cohu",
    "FORM": "FormFactor", "AMBA": "Ambarella", "CEVA": "CEVA Inc.",
    "SLAB": "Silicon Labs", "DIOD": "Diodes Inc.", "ALGM": "Allegro Micro",
    "AXTI": "AXT Inc.", "SITM": "SiTime", "ALAB": "Astera Labs",
    "ONTO": "Onto Innovation", "ENTG": "Entegris", "UCTT": "Ultra Clean",
    "ICHR": "Ichor Holdings", "KLIC": "Kulicke & Soffa", "RMBS": "Rambus", "CRUS": "Cirrus Logic",
    # Software / Cloud / AI
    "PLTR": "Palantir", "CRWD": "CrowdStrike", "SNOW": "Snowflake",
    "NET": "Cloudflare", "DDOG": "Datadog", "MDB": "MongoDB", "HUBS": "HubSpot",
    "ZS": "Zscaler", "OKTA": "Okta", "PANW": "Palo Alto Networks", "FTNT": "Fortinet",
    "RPD": "Rapid7", "S": "SentinelOne", "ASAN": "Asana", "BILL": "Bill.com",
    "CFLT": "Confluent", "GTLB": "GitLab", "ESTC": "Elastic", "DT": "Dynatrace",
    "DOCN": "DigitalOcean", "FSLY": "Fastly", "CWAN": "Clearwater Analytics",
    "FOUR": "Shift4 Payments", "PATH": "UiPath", "AI": "C3.ai",
    "BBAI": "BigBear.ai", "SOUN": "SoundHound AI", "BRZE": "Braze",
    "FRSH": "Freshworks", "DOMO": "Domo", "APP": "AppLovin",
    "APLD": "Applied Digital", "IONQ": "IonQ", "RGTI": "Rigetti Computing",
    "QUBT": "Quantum Computing", "QBTS": "D-Wave Quantum",
    "TTD": "The Trade Desk", "MGNI": "Magnite", "PUBM": "PubMatic",
    "CXAI": "CX AI", "GFAI": "Guardforce AI",
    "RBLX": "Roblox", "U": "Unity Software", "SHOP": "Shopify",
    "MELI": "MercadoLibre", "SE": "Sea Limited", "GRAB": "Grab Holdings",
    "PCVX": "Vaxcyte", "DAVE": "Dave Inc.", "MQ": "Marqeta",
    # Fintech
    "SOFI": "SoFi Technologies", "HOOD": "Robinhood", "COIN": "Coinbase",
    "MSTR": "MicroStrategy", "AFRM": "Affirm", "UPST": "Upstart",
    "LMND": "Lemonade", "HIMS": "Hims & Hers", "WEX": "WEX Inc.",
    "GPN": "Global Payments", "FIS": "Fidelity National Info",
    "FISV": "Fiserv", "V": "Visa", "AXP": "American Express",
    "SYF": "Synchrony Financial", "COF": "Capital One",
    "ALLY": "Ally Financial", "OPEN": "Opendoor",
    # Crypto-adjacent
    "MARA": "Marathon Digital", "RIOT": "Riot Platforms", "HUT": "Hut 8 Mining",
    "CLSK": "CleanSpark", "IREN": "Iris Energy", "BITF": "Bitfarms",
    "CIFR": "Cipher Mining", "BTBT": "Bit Digital", "WULF": "TeraWulf", "CORZ": "Core Scientific",
    # Biotech / Pharma / Health
    "LLY": "Eli Lilly", "ABBV": "AbbVie", "MRK": "Merck", "PFE": "Pfizer",
    "TMO": "Thermo Fisher", "ABT": "Abbott Labs", "DHR": "Danaher",
    "BMY": "Bristol-Myers Squibb", "AMGN": "Amgen", "GILD": "Gilead Sciences",
    "BIIB": "Biogen", "REGN": "Regeneron", "VRTX": "Vertex Pharma",
    "ISRG": "Intuitive Surgical", "BSX": "Boston Scientific",
    "SYK": "Stryker", "MDT": "Medtronic", "BDX": "Becton Dickinson",
    "RMD": "ResMed", "IQV": "IQVIA", "MRNA": "Moderna",
    "BNTX": "BioNTech", "NVAX": "Novavax", "SRPT": "Sarepta Therapeutics",
    "BMRN": "BioMarin Pharma", "ALNY": "Alnylam Pharma", "RARE": "Ultragenyx",
    "PTCT": "PTC Therapeutics", "FOLD": "Amicus Therapeutics",
    "TGTX": "TG Therapeutics", "PRAX": "Praxis Precision Medicine",
    "IMVT": "Immunovant", "ARWR": "Arrowhead Pharma", "BEAM": "Beam Therapeutics",
    "EDIT": "Editas Medicine", "NTLA": "Intellia Therapeutics",
    "CRSP": "CRISPR Therapeutics", "KYMR": "Kymera Therapeutics",
    "KROS": "Keros Therapeutics", "ABCL": "AbCellera Bio",
    "VKTX": "Viking Therapeutics", "GPCR": "Structure Therapeutics",
    "RXRX": "Recursion Pharma", "ACAD": "Acadia Pharma",
    "HALO": "Halozyme", "CELH": "Celsius Holdings",
    "INVA": "Innoviva", "RVMD": "Revolution Medicines",
    "PTGX": "Protagonist Therapeutics", "AGIO": "Agios Pharma",
    # Consumer Discretionary
    "HD": "Home Depot", "LOW": "Lowe's", "MCD": "McDonald's",
    "SBUX": "Starbucks", "TJX": "TJX Companies", "ROST": "Ross Stores",
    "BKNG": "Booking Holdings", "MAR": "Marriott", "HLT": "Hilton",
    "CMG": "Chipotle", "YUM": "Yum! Brands", "DRI": "Darden Restaurants",
    "DKNG": "DraftKings", "ETSY": "Etsy", "EBAY": "eBay", "ABNB": "Airbnb",
    "LVS": "Las Vegas Sands", "MGM": "MGM Resorts", "WYNN": "Wynn Resorts",
    "PENN": "Penn Entertainment", "F": "Ford Motor", "GM": "General Motors",
    "RIVN": "Rivian", "LCID": "Lucid Motors", "CAVA": "CAVA Group",
    "SHAK": "Shake Shack", "TXRH": "Texas Roadhouse", "WING": "Wingstop",
    "ONON": "On Holding", "CROX": "Crocs", "FND": "Floor & Decor",
    "RH": "RH (Restoration Hardware)", "LYFT": "Lyft",
    # Consumer Staples
    "PG": "Procter & Gamble", "KO": "Coca-Cola", "PEP": "PepsiCo",
    "COST": "Costco", "WMT": "Walmart", "TGT": "Target",
    "MDLZ": "Mondelez", "GIS": "General Mills", "CPB": "Campbell's",
    "HSY": "Hershey", "MKC": "McCormick", "CLX": "Clorox",
    "CL": "Colgate-Palmolive", "EL": "Estée Lauder",
    # Energy
    "XOM": "ExxonMobil", "CVX": "Chevron", "COP": "ConocoPhillips",
    "EOG": "EOG Resources", "OXY": "Occidental Petroleum",
    "MPC": "Marathon Petroleum", "VLO": "Valero Energy", "PSX": "Phillips 66",
    "DVN": "Devon Energy", "APA": "APA Corp", "HAL": "Halliburton",
    "SLB": "SLB (Schlumberger)", "BKR": "Baker Hughes",
    "NOV": "NOV Inc.", "FANG": "Diamondback Energy",
    "CTRA": "Coterra Energy", "SM": "SM Energy", "MTDR": "Matador Resources",
    "CRGY": "Crescent Energy", "CHRD": "Chord Energy",
    "PR": "Permian Resources", "ROCC": "Ranger Oil", "TALO": "Talos Energy",
    # Financials
    "GS": "Goldman Sachs", "MS": "Morgan Stanley", "BAC": "Bank of America",
    "WFC": "Wells Fargo", "C": "Citigroup", "BLK": "BlackRock",
    "SCHW": "Charles Schwab", "CME": "CME Group", "ICE": "Intercontinental Exchange",
    "CBOE": "Cboe Global Markets", "NTRS": "Northern Trust", "STT": "State Street",
    "BK": "BNY Mellon", "USB": "U.S. Bancorp", "PNC": "PNC Financial",
    "RF": "Regions Financial", "CFG": "Citizens Financial",
    "HBAN": "Huntington Bancshares", "KEY": "KeyCorp",
    "TFC": "Truist Financial", "MTB": "M&T Bank",
    "ZION": "Zions Bancorporation", "OFG": "OFG Bancorp",
    "UWMC": "UWM Holdings", "RKT": "Rocket Companies",
    "MKTX": "MarketAxess",
    # Industrials / Defense
    "LMT": "Lockheed Martin", "RTX": "RTX Corp", "BA": "Boeing",
    "NOC": "Northrop Grumman", "GD": "General Dynamics",
    "TDG": "TransDigm", "GE": "GE Aerospace", "HON": "Honeywell",
    "MMM": "3M", "EMR": "Emerson Electric", "ETN": "Eaton",
    "PH": "Parker Hannifin", "ROK": "Rockwell Automation",
    "AME": "AMETEK", "GNRC": "Generac", "OTIS": "Otis Worldwide",
    "CARR": "Carrier Global", "ITW": "Illinois Tool Works",
    "XYL": "Xylem", "KTOS": "Kratos Defense", "AXON": "Axon Enterprise",
    "LDOS": "Leidos", "SAIC": "SAIC", "BAH": "Booz Allen Hamilton",
    "CACI": "CACI International", "HII": "Huntington Ingalls",
    "JOBY": "Joby Aviation", "ACHR": "Archer Aviation",
    "EVTL": "Vertical Aerospace", "SPCE": "Virgin Galactic",
    # Materials
    "LIN": "Linde", "APD": "Air Products", "DD": "DuPont",
    "DOW": "Dow Inc.", "PPG": "PPG Industries", "SHW": "Sherwin-Williams",
    "NEM": "Newmont", "FCX": "Freeport-McMoRan", "AA": "Alcoa",
    "CLF": "Cleveland-Cliffs", "NUE": "Nucor", "STLD": "Steel Dynamics",
    "RS": "Reliance Steel", "VMC": "Vulcan Materials", "MLM": "Martin Marietta",
    "FMC": "FMC Corp", "MOS": "Mosaic", "CF": "CF Industries", "MP": "MP Materials",
    # Utilities
    "NEE": "NextEra Energy", "DUK": "Duke Energy", "SO": "Southern Company",
    "D": "Dominion Energy", "AEP": "American Electric Power",
    "EXC": "Exelon", "PCG": "PG&E", "XEL": "Xcel Energy",
    "WEC": "WEC Energy", "ES": "Eversource", "CMS": "CMS Energy",
    "AWK": "American Water Works", "SRE": "Sempra", "ETR": "Entergy",
    # Communication / Media
    "T": "AT&T", "VZ": "Verizon", "TMUS": "T-Mobile", "DIS": "Disney",
    "NFLX": "Netflix", "CMCSA": "Comcast", "CHTR": "Charter Comm.",
    "FOXA": "Fox Corp", "WBD": "Warner Bros. Discovery",
    "EA": "Electronic Arts", "TTWO": "Take-Two Interactive",
    "MTCH": "Match Group", "ZM": "Zoom", "SNAP": "Snap",
    "PINS": "Pinterest", "ROKU": "Roku", "SPOT": "Spotify",
    # Real Estate / REITs
    "AMT": "American Tower", "PLD": "Prologis", "EQIX": "Equinix",
    "CCI": "Crown Castle", "SPG": "Simon Property", "O": "Realty Income",
    "AVB": "AvalonBay", "EQR": "Equity Residential",
    "DLR": "Digital Realty", "WELL": "Welltower", "VTR": "Ventas",
    # Space / Defense-adjacent
    "ASTS": "AST SpaceMobile", "OKLO": "Oklo", "LUNR": "Intuitive Machines",
    "RKLB": "Rocket Lab", "IRDM": "Iridium Comm.", "SPIR": "Spire Global",
    # Meme / High-beta retail
    "GME": "GameStop", "AMC": "AMC Entertainment", "ARQQ": "Arqit Quantum",
    # ETFs — Broad market
    "SPY": "S&P 500 ETF", "QQQ": "Nasdaq 100 ETF", "DIA": "Dow Jones ETF",
    "VTI": "Total Market ETF", "VOO": "Vanguard S&P 500", "IVV": "iShares S&P 500",
    # ETFs — Mid / small cap
    "MDY": "S&P MidCap 400", "IJH": "iShares MidCap", "IJR": "iShares SmallCap",
    "VB": "Vanguard Small-Cap", "IWO": "Russell 2000 Growth", "IWN": "Russell 2000 Value",
    # ETFs — Sector
    "XLK": "Tech Sector ETF", "XLF": "Financial Sector ETF",
    "XLE": "Energy Sector ETF", "XLV": "Health Sector ETF",
    "XLI": "Industrial Sector ETF", "XLC": "Comm. Sector ETF",
    "XLY": "Consumer Disc. ETF", "XLP": "Consumer Staples ETF",
    "XLB": "Materials Sector ETF", "XLRE": "Real Estate ETF", "XLU": "Utilities ETF",
    # ETFs — Thematic
    "SOXX": "Semiconductor ETF", "SMH": "VanEck Semis ETF",
    "HACK": "Cybersecurity ETF", "CIBR": "Cybersecurity ETF (First Trust)",
    "WCLD": "Cloud Computing ETF", "BUG": "Global X Cybersecurity",
    "ARKG": "ARK Genomic ETF", "ARKF": "ARK Fintech ETF",
    "GLD": "Gold ETF", "SLV": "Silver ETF",
    "GDX": "Gold Miners ETF", "GDXJ": "Junior Gold Miners",
    "USO": "Oil ETF", "UNG": "Natural Gas ETF",
    "TLT": "20yr Treasury ETF", "HYG": "High Yield Bond ETF",
    "LQD": "Investment Grade Bond", "TIP": "TIPS Bond ETF",
    # ETFs — Leveraged
    "TQQQ": "3x Nasdaq Bull", "SQQQ": "3x Nasdaq Bear",
    "UPRO": "3x S&P 500 Bull", "SPXU": "3x S&P 500 Bear",
    "SOXL": "3x Semis Bull", "SOXS": "3x Semis Bear",
    "UVXY": "1.5x VIX ETF", "SVXY": "-0.5x VIX ETF",
    "LABU": "3x Biotech Bull", "LABD": "3x Biotech Bear",
    # Additional tickers sometimes in universe
    "CBRS": "Cerebras Systems",
}
